mindmap
  root((Case Type))
    Data Model
      Properties
      Data Types
      Embedded Pages
    Stages
      Processes
        Flows
          Assignments
          Decisions
          Utilities
    UI
      Views / Sections
      Flow Actions
      Portals
    Integrations
      Data Pages
      Connectors
    Security
      Roles
      Access When
    SLAs
      Stage SLA
      Assignment SLA
