"""One-page romantic study recap per chapter — readable, not a wall of tables."""

STUDY_RECAP: dict[int, str] = {
    1: "Pega is not just software — it's a love story between business and technology. Cases are your chapters, stages are plot twists, and rules are the promises you keep. Six layers stack like a perfect date plan: UI, process, decisions, data, integration, security. App Studio flirts; Dev Studio commits. Center-out means you design once and charm every channel. Walk into interview saying: BPM + CRM + case management on one low-code platform with guardrails that keep you out of trouble.",
    2: "Classes are family trees — inheritance is how Pega finds the right rule without drama. Pattern inheritance is automatic (like knowing your partner's coffee order). Directed inheritance is when you consciously choose to borrow from another branch. Class groups are work pools sharing one table. Rule resolution always starts at the leaf class and walks up. Draw the hierarchy; interviewers melt.",
    3: "Rule resolution is Pega's ten-step treasure hunt: class, name, ruleset, availability, blocked, specificity, version, circumstance, available, FUA cache. Circumstance is the plot twist — same rule, different date or property value. Withdrawn, blocked, final — know the drama words. FUA means second lookup is instant. This chapter is interview royalty — memorize it like a love poem.",
    4: "Your application stack is the wedding registry — built-on apps, rulesets in order, versions locked. Ruleset naming MM-mm-nn is non-negotiable. Branches let you flirt with features without breaking prod. RAP is the gift box you ship to QA and prod. Skim, merge, deploy — say it smoothly.",
    5: "A case is one business heartbeat — loan, claim, complaint. Stages are acts; processes are scenes; assignments are who picks up the phone. pyDefault is the main flow. Cover cases parent children; spin-offs create side stories. Status pyStatusWork tells you where you stand. Lifecycle diagrams win hearts and offers.",
    6: "Flows automate; flow actions are the buttons users actually press. Eight shapes: Start, Assignment, Decision, Subprocess, Split-Join, Split-ForEach, Utility, End. Local vs connector flow actions — same screen vs new screen. Wait shape pauses for timer or event. Utility = no human needed. Draw shapes from memory.",
    7: "Assignments are tasks waiting for someone charming to resolve them. Worklist = personal inbox. Workbasket = team tray. Routing: standard, custom, skill-based, round-robin. Urgency pxUrgencyAssign sorts the queue. Transfer, delegate, approve — know the verbs. SLA ties here — deadlines create healthy pressure.",
    8: "Clipboard is Pega's short-term memory during a request. pyWorkPage = case data. pxRequestor = logged-in user. pxThread = open assignments. Page List = ordered list; Page Group = named map. Property types matter — text, integer, date, page, page list. Keep clipboard lean; guardrails warn above 2MB.",
    9: "Data Pages are the modern love language — declare what you need, Pega fetches and caches. Read-only vs editable, list vs singleton, reload once vs per interaction. Prefer Data Page over RDB-List every time. Save plan for editable reference data. Say it with confidence: smart, cached, declarative data access.",
    10: "Data Transforms map clipboard like writing a thoughtful note — Set, Update Page, When, ForEach, Append. Always before Activity in the guardrail gospel. Auto-populate properties can call DTs. ForEach over page lists is your loop replacement. Interview answer: DT for 99% of data mapping.",
    11: "Activities are the ex you call only when necessary — loops, legacy, special steps. Steps: Property-Set, Obj-Open, Call, Branch. Restricted activities need allow lists. Tracer shows every step. Say: Activity last resort; DT and Data Page first. Know Obj- methods anyway.",
    12: "Decisions are Pega's brain. When = one question. Decision Table = spreadsheet of outcomes. MapValue = lookup. Scorecard = weighted score. Decision Tree = if-else ladder. Strategy = CDH engine. Pick the right tool — table for combos, When for simple gates.",
    13: "Declare rules auto-magic your data. Expression = computed field with forward chaining. OnChange = react to property edits. Constraint = validation at property level. Trigger = on Data- commit. Index = search performance. Declares are declarative elegance — say you minimize manual recalc.",
    14: "Validation protects hearts and data. Validate rule on flow action. Edit Validate on UI fields. Constraint on properties. Error messages must be human-readable. Client + server validation story impresses. pyMessage for field errors.",
    15: "UI is how users fall in love with your app. Traditional: Harness + Section. Constellation: View + Theme + DX API + React. Cosmos design system for modern look. Portal = shell. Dynamic layout over freeform. Migration story: Sections → Views, feature toggle rollback.",
    16: "SLA is the gentle nudge that becomes an alarm. Goal, Deadline, Passed Deadline — three acts. Urgency climbs as time runs out. Assignment vs stage SLA. Agent ServiceLevelEvents processes queues. Escalation routes to manager. Business time calendars matter.",
    17: "Integration is Pega reaching out (Connect) or welcoming in (Service). REST is king — JSON mapping, auth profiles, OAuth. Data types manage Data- classes. Connect-REST + Data Page is the modern pattern. Error handling and timeouts — always mention them.",
    18: "Security is layered trust. Operator → Access Group → Role → Privilege → Access When. ABAC via property conditions. Property security on sensitive fields. Authentication service for custom login. Audit when they ask about compliance.",
    19: "Agents are background cupids — async work while users sleep. Queue-For-Agent defers processing. Job Scheduler replaces some legacy agents. Standard agents: ServiceLevel, Pega-Auto, etc. Enable/disable per node. Know agent vs job scheduler for Infinity.",
    20: "Reports answer business questions. Report Definition = SQL rule. Summary vs list views. Association joins tables. Drill-down for detail. Prefer Report Def over RDB-List in activities. pxResults holds output.",
    21: "Testing is proof you care. Unit test = single rule. Scenario test = full UI path. Test ruleset isolates tests. Run from App Studio or Dev Studio. Coverage before release — say it in interview.",
    22: "Performance is respect for users' time. PAL first — pxRDBIO, clipboard size. Tracer for deep dive. N+1 loop Obj-Open = villain. Fix with batch Data Page. Guardrails score tracks health. Ten guardrails from memory.",
    23: "DevOps is how love ships safely. Branch → merge → RAP → Deployment Manager → QA → Prod. Repository = Git for rules. Skim removes orphans. Rollback plan always. CI/CD story separates seniors from juniors.",
    24: "Correspondence is Pega writing love letters — email, PDF, attachments. Correspondence rule + email account. Send Email shape in flow. AttachAsPDF for documents. Inbound email service creates or updates cases.",
    25: "Advanced Pega: CDH decides next best action, strategies rank offers, RPA handles desktop robots, Prediction Studio trains models. NBA = right offer, right channel, right time. Mention GenAI Socrates if they want modern flavor.",
    26: "Controls and metadata polish the experience. Field Value drives dropdowns. Localization for multi-language. Control rules for custom widgets. pyCaption for labels. Details interviewers skip — until they don't.",
    27: "Object layer is truth in the database. Obj-Open reads, Obj-Save writes, Commit persists, Rollback undoes. pzInsKey is the unique handle. pxCommitDateTime for audit. Transaction boundary — one request, one story.",
}


def study_recap_box(chapter_num: int) -> str:
    text = STUDY_RECAP.get(chapter_num, "")
    if not text:
        return ""
    return f'<div class="flirt-box"><strong>💕 Chapter Recap (read this first):</strong> {text}</div>'
